# Enable Vi mode
setw -g mode-keys vi
# Set the default shell explicitly
set -g default-shell "$SHELL"
# Tell tmux to use 256-color internally
set -g default-terminal "screen-256color"
# Allow tmux to send 256-color to its "parent terminal"
set -ga terminal-overrides ",*-256color*:TC"
